### ISSUE TITLE
Infinite scroll throw with Safari

### ISSUE THREAD

**Issue by trungtin** [OnsenUI/react-onsenui-kitchensink#1]
```
Error: wrapperElement must be {"prototype":{"ALLOW_KEYBOARD_INPUT":1},"ALLOW_KEYBOARD_INPUT":1}.
You provided [object HTMLUnknownElement]
```

as this function call `this._wrapperElement = util.validated('wrapperElement', wrapperElement, Element);` in `LazyRepeatProvider`. It's seem this is problem with Onsenui itself, I'm using OnsenUI-dist.git#2.0.0-react.5 .

**Comment by argelius** [comment]
We tried it on Safari and it looks like this issue has been solved. Are you still having trouble?

**Comment by trungtin** [comment]
Right, beta.10 still got problem, but upgrade to beta.14 fixed it, thanks man :)
