### ISSUE TITLE
Pull to refresh doesn't work and poor Android styles

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/react-onsenui-kitchensink#2]
Pull to refresh doesn't work. Bug or not yet implemented?
Also, Android styling is poor. Not yet fully implemented?
Using latest onsenui and react-onsenui.

**Comment by argelius** [comment]
Thanks for reporting @mishoboss !

In what way is it poor? Right now the tabs with both icon and text label look a bit strange on Android. Is there something else?

There was also an issue with the list but that has been fixed here:
http://onsenui.github.io/react-onsenui-kitchensink/demo.html

**Comment by mishoboss** [comment]
Hi, maybe something wrong with my setup, because I get a lot of console errors and some missing styles. I'll try to investigate.

**Comment by argelius** [comment]
Thank you @mishoboss ! What browser are you using?

**Comment by mishoboss** [comment]
Chrome. But not the browser is the problem. Probably my webpack is messing with me. Is there any working example with webpack?

**Comment by mishoboss** [comment]
Using onsenui 2.0.0-beta.13 this is gone now

**Comment by argelius** [comment]
I will try creating a webpack example. All the examples we have are using browserify but it should work with webpack as well.
