### ISSUE TITLE
Uncaught TypeError: Cannot set property 'checked' of null

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/react-onsenui-kitchensink#3]
This is on latest version:

`onsenui.js:22606 Uncaught TypeError: Cannot set property 'checked' of nullsetActive @ onsenui.js:22606setActiveTab @ onsenui.js:22158componentDidMount @ react-onsenui.js:1865_assign.notifyAll @ CallbackQueue.js:66ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js:79Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149Mixin.perform @ Transaction.js:136_assign.perform @ ReactUpdates.js:89flushBatchedUpdates @ ReactUpdates.js:165ReactUpdates_flushBatchedUpdates @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:97ReactMount._renderNewRootComponent @ ReactMount.js:277ReactMount__renderNewRootComponent @ ReactPerf.js:66ReactMount._renderSubtreeIntoContainer @ ReactMount.js:354ReactMount.render @ ReactMount.js:374React_render @ ReactPerf.js:66(anonymous function) @ main.js:70__webpack_require__ @ bootstrap a3eb468…:19(anonymous function) @ bootstrap a3eb468…:39(anonymous function) @ bootstrap a3eb468…:39`

**Comment by mishoboss** [comment]
Using 2.0.0-beta.13 this is gone

**Comment by argelius** [comment]
@mishoboss Great! :+1: 

Thanks for reporting these issues it's really appreciated

**Comment by lirenhao** [comment]
I have the same error in the latest version
