### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by steodor** [OnsenUI/react-onsenui-kitchensink#5]
Current dependencies:

```
"react": "^15.1.0",
"react-dom": "^15.1.0",
"onsenui": "^2.0.0-rc.15",
"react-onsenui": "^0.7.3",
```

Latest versions:

```
"react": "^15.3.2",
"react-dom": "^15.3.2",
"onsenui": "^2.3.1",
"react-onsenui": "^1.3.3",
```

While the `react` and `react-dom` dependencies are relatively ok, the `onsenui` and `react-onsenui` deps are critically out of date.

Last commit is ~10 months old and this raises a question: is anybody maintaining this repo at all?

L.E.: thanks for the answer! 👍

**Comment by asialgearoid** [comment]
Closed by #6.
